class DataKeys {
  static LIST_OF_IDS = 'DATA_TODO__LIST_OF_IDS';
  static LIST_OF_IDS_VISIBLE = 'DATA_TODO__LIST_OF_IDS_VISIBLE';
  static NOT_COMPLETED_COUNT = 'DATA_TODO__NOT_COMPLETED_COUNT';
  static COMPLETE_ALL = 'COMPLETE_ALL';
  static FILTER = 'DATA_TODO__FILTER';
}

export default DataKeys;
