class ViewSignals {
  static INPUT = 'SIGNAL__INPUT_TODO';
  static EDIT = 'SIGNAL__EDIT_TODO';
  static DELETE = 'SIGNAL__DELETE_TODO';
  static DISMISSED = 'SIGNAL__DISMISSED_TODO';
  static TOGGLE = 'SIGNAL__TOGGLE_TODO';
  static FILTER = 'SIGNAL__FILTER_TODO';
  static CLEAR_INPUT = 'SIGNAL__CLEAR_TODO';
  static CLEAR_COMPLETED = 'SIGNAL__CLEAR_COMPLETED';
  static COMPLETE_ALL = 'SIGNAL__COMPLETE_ALL';
  static COMPLETE_ALL_FORCED = 'SIGNAL__COMPLETE_ALL_FORCED';
}

export default ViewSignals;
